application: browserscope-demo
version: 1
runtime: python
api_version: 1

skip_files: |
  (.*static/closure.*)|
  (.*~)|
  (\..*)

handlers:

- url: /local
  static_files: static/index_local.html
  upload: /.*

- url: /.*
  static_files: static/index.html
  upload: /.*

- url: /static
  static_dir: static

